version: '3.1'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "shop"
      POSTGRES_USER: "Masters"
      POSTGRES_PASSWORD: "Academy"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes: 
  pgdata:
